import { ProductStatus } from './product-status.enum';
import { Product } from './product.entity';

export const data: Product[] = [
  {
    id: '1',
    name: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    price: 10995,
    description:
      'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    category: "men's clothing",
    categoryImage:
      'https://www.realmenrealstyle.com/wp-content/uploads/2021/05/body-types.jpg',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    rating: 2.9,
    reviews: 470,
    stock: 35,
    brand: 'Nike',
    store: 'Ndiaye Et Frere',
    location: 'Dakar',
    status: ProductStatus.IMPORTE,
  },
  {
    id: '2',
    name: 'Mens Casual Premium Slim Fit T-Shirts ',
    price: 22300,
    description:
      'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.',
    category: "men's clothing",
    categoryImage:
      'https://www.realmenrealstyle.com/wp-content/uploads/2021/05/body-types.jpg',
    image:
      'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
    rating: 2.9,
    reviews: 470,
    stock: 35,
    brand: 'Nike',
    location: 'Dakar',
    store: 'Ndiaye Et Frere',
    status: ProductStatus.IMPORTE,
  },
  {
    id: '3',
    name: 'Mens Cotton Jacket',
    price: 5599,
    description:
      'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.',
    category: "men's clothing",
    categoryImage:
      'https://www.realmenrealstyle.com/wp-content/uploads/2021/05/body-types.jpg',
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    rating: 2.9,
    reviews: 470,
    stock: 35,
    brand: 'Nike',
    store: 'Ndiaye Et Frere',
    location: 'Dakar',
    status: ProductStatus.IMPORTE,
  },
  {
    id: '4',
    name: 'Mens Casual Slim Fit',
    price: 15990,
    description:
      'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.',
    category: "men's clothing",
    categoryImage:
      'https://www.realmenrealstyle.com/wp-content/uploads/2021/05/body-types.jpg',
    image: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    rating: 2.9,
    reviews: 470,
    stock: 35,
    store: 'Ndiaye Et Frere',
    location: 'Dakar',
    brand: 'Nike',
    status: ProductStatus.IMPORTE,
  },
  {
    id: '5',
    name: "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
    price: 6950,
    description:
      "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
    category: 'jewelery',
    categoryImage:
      'https://www.krishnajewellers.com/blog/wp-content/uploads/2021/07/RV_10-1100x734.jpg',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    rating: 2.9,
    reviews: 470,
    stock: 35,
    brand: 'Nike',
    store: 'Sen Fashion',
    location: 'Mbour',
    status: ProductStatus.IMPORTE,
  },
  {
    id: '6',
    name: 'Solid Gold Petite Micropave ',
    price: 16800,
    description:
      'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.',
    category: 'jewelery',
    categoryImage:
      'https://www.krishnajewellers.com/blog/wp-content/uploads/2021/07/RV_10-1100x734.jpgda1e9a76/BeFunky_collage___2020_12_04T165317_155.jpg?w=1200&h=675',
    image: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
    rating: 2.9,
    reviews: 470,
    stock: 35,
    brand: 'Nike',
    store: 'Sen Fashion',
    location: 'Mbour',
    status: ProductStatus.IMPORTE,
  },
  {
    id: '7',
    name: 'White Gold Plated Princess',
    price: 9990,
    description:
      "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
    category: 'jewelery',
    categoryImage:
      'https://www.krishnajewellers.com/blog/wp-content/uploads/2021/07/RV_10-1100x734.jpgda1e9a76/BeFunky_collage___2020_12_04T165317_155.jpg?w=1200&h=675',
    image: 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg',
    rating: 2.9,
    reviews: 470,
    store: 'Sen Fashion',
    location: 'Mbour',
    stock: 35,
    status: ProductStatus.IMPORTE,
    brand: 'Nike',
  },
  {
    id: '8',
    name: 'Pierced Owl Rose Gold Plated Stainless Steel Double',
    price: 10990,
    description:
      'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel',
    category: 'jewelery',
    categoryImage:
      'https://www.krishnajewellers.com/blog/wp-content/uploads/2021/07/RV_10-1100x734.jpgda1e9a76/BeFunky_collage___2020_12_04T165317_155.jpg?w=1200&h=675',
    image: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
    rating: 2.9,
    reviews: 470,
    stock: 35,
    brand: 'Nike',
    status: ProductStatus.IMPORTE,
    store: 'Sen Fashion',
    location: 'Mbour',
  },
  {
    id: '9',
    name: 'WD 2TB Elements Portable External Hard Drive - USB 3.0 ',
    price: 6400,
    description:
      'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system',
    category: 'electronics',
    categoryImage:
      'https://media-exp1.licdn.com/dms/image/C4E1BAQGENeCDJ5VXPg/company-background_10000/0/1559151958971?e=2159024400&v=beta&t=aVOx6JocN4tZFBf4ssICncreN4NSR3X86Btrn_WtTbk',
    image: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg',
    rating: 2.9,
    reviews: 470,
    stock: 35,
    brand: 'Nike',
    status: ProductStatus.LOCAL,
    store: 'Sen Electro',
    location: 'Kaolack',
  },
  {
    id: '10',
    name: 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s',
    price: 10900,
    description:
      'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)',
    category: 'electronics',
    categoryImage:
      'https://media-exp1.licdn.com/dms/image/C4E1BAQGENeCDJ5VXPg/company-background_10000/0/1559151958971?e=2159024400&v=beta&t=aVOx6JocN4tZFBf4ssICncreN4NSR3X86Btrn_WtTbk',
    image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
    rating: 2.9,
    reviews: 470,
    stock: 35,
    brand: 'Nike',
    status: ProductStatus.LOCAL,
    store: 'Sen Electro',
    location: 'Kaolack',
  },
];
